version = 1

test_patterns = ["**/*.test.js"]

exclude_patterns = [
    ".github",
    ".vscode",
    "yarn.lock"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "standardjs"
enabled = true