name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-react-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn run test
